server:
  port: 8009

spring:
  application:
    name: quote-service
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
      config:
        enabled: false
        server-addr: localhost:8848
        file-extension: yml
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dailybaro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isdelete
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.dailybaro.quote: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
