server:
  port: 8008

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dailybaro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# AI服务配置
deepseek:
  api-url: https://api.deepseek.com/v1/chat/completions
  api-key: sk-92d68b33753d4ab88721f7abbe4713fa

logging:
  level:
    com.dailybaro.ai: debug 