server:
  port: 8003

spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

file:
  upload-dir: ./uploads

logging:
  level:
    com.dailybaro.file: debug 